### PR TITLE
Add BlueCard with tests

### PR DESCRIPTION
**Pull request by Git-Tonio**

### CODE REVIEW

**Comment by J0c4** [comment]
Hi @Git-Tonio , changes look good, please do a rebase so we can merge this PR

**Comment by J0c4** [comment]
Hi @Git-Tonio , please don't forget to do rebase, I'll be merging PRs that are rebased already

**Comment by Git-Tonio** [comment]
I already made the rebase, I wait for the approval

**Comment by J0c4** [comment]
Hi @Git-Tonio , sorry, I think Rodrigo was faster while I went to have lunch, please rebase once more and I'll merge as soon as you have it

image

**Pull request merged**
